elastic:
  username: elastic
  password: changeme
  uri: http://localhost:9200
openAi:
  token: ...
amqp:
  url: "{AMQP_URL}"
discord:
  token: "{TOKEN}"
deploy:
  port: "{PORT}"
mongo:
  uri: "${MONGO_URI}"
wombo-dream:
  api:
    url: "https://paint.api.wombo.ai/api"
  googleAuthUrl: "https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=AIzaSyDCvp5MTJLUdtBYEKYWXJrlLzu1zuKM6Xw"