name: Run tests an upload coverage

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test:cov
      - name: Push coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          name: ${{ github.sha }}
          fail_ci_if_error: true
          verbose: true
